<?php
declare(strict_types=1);

namespace Mine\Command\Creater;

use Hyperf\Command\Annotation\Command;
use Mine\MineCommand;

/**
 * Class CreateModule
 * @Command
 * @package System\Command\Creater
 */
class CreateModule extends MineCommand
{
    protected $name = 'mine:module-gen';

    protected function configure()
    {
        parent::configure(); // TODO: Change the autogenerated stub
    }

    public function handle()
    {
        // TODO: Implement handle() method.
    }
}